### ISSUE TITLE
React warns about componentWillReceiveProps

### ISSUE THREAD

**Issue by ertrzyiks** [toptal/simple-react-calendar#123]
### Are you submitting a **bug report** or a **feature request**?
Using React 16 this module generates runtime warnings
```
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this 
warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all 
deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-
lifecycles` in your project source folder.
```

### What is the current behavior?
I see the warning. 

### What is the expected behavior?
I see no warning. 

### What's your environment?
react@16.12.0

**Comment by havenchyk** [comment]
Done by #216
