### ISSUE TITLE
css for the calendar?

### ISSUE THREAD

**Issue by mathishuettl** [toptal/simple-react-calendar#184]
Hello guys,

it seems to be a stupid question, but when i import the calendar and use it in react it issnt styled - i also cant find any styles in the source-code? can you help me?

**Comment by havenchyk** [comment]
@mathishuettl not a stupid question. We don't deliver styles by default currently, so you have two ways to add styling

1) to use completely custom styles https://github.com/toptal/simple-react-calendar#class-names
2) to use some styles from examples https://github.com/toptal/simple-react-calendar/tree/master/src/example/style

**Comment by havenchyk** [comment]
@mathishuettl I'm closing this issue. If you think that something can be clarified or improved, feel free to reopen.
