### ISSUE TITLE
Add storybook support? 

### ISSUE THREAD

**Issue by havenchyk** [toptal/simple-react-calendar#38]
Something like in [airbnb-dates](http://airbnb.io/react-dates/?selectedKind=DateRangePicker&selectedStory=vertical&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

**Comment by PeterMK85** [comment]
Github PR:
https://github.com/toptal/simple-react-calendar/pull/64
