### ISSUE TITLE
Invalid build for `1.6.0` version

### ISSUE THREAD

**Issue by paraboom** [toptal/simple-react-calendar#49]
Hey, guys. I tried to use calendar with React 16 and installed `1.6.0` version. And I noticed in `lib/calendar/_lib/index.js` there is a wrong link to `PropTypes`. Here is a content of that file:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.datePropType = undefined;

var _react = require('react');

var datePropType = exports.datePropType = _react.PropTypes.oneOfType([_react.PropTypes.number, _react.PropTypes.string, _react.PropTypes.instanceOf(Date)]);
```

`PropTypes` was imported from `react`. Can you re-upload the package, please?

**Comment by paraboom** [comment]
Oh, I see. The latest changes were not published to npm. Can you do it please?

**Comment by PeterMK85** [comment]
Prepared the release:

https://github.com/toptal/simple-react-calendar/pull/55

**Comment by PeterMK85** [comment]
@paraboom 
SimpleReactCalendar 1.7.0 has been released
https://www.npmjs.com/package/simple-react-calendar
